import { z } from "zod";

/**
 * Zod schema for validating workflow blueprints generated by AI
 * This matches the structure required for Level 2 workflow generation
 */
export const WorkflowBlueprintSchema = z.object({
  name: z.string().min(1, "Name is required"),
  description: z.string().optional(),
  trigger: z.object({
    type: z.string().min(1, "Trigger type is required"),
    app: z.string().min(1, "Trigger app is required"),
    config: z.record(z.string(), z.any()).default({}),
  }),
  actions: z.array(
    z.object({
      type: z.string().min(1, "Action type is required"),
      app: z.string().min(1, "Action app is required"),
      operation: z.string().min(1, "Action operation is required"),
      config: z.record(z.string(), z.any()).default({}),
    })
  ).min(1, "At least one action is required"),
});

export type WorkflowBlueprint = z.infer<typeof WorkflowBlueprintSchema>;

